### ISSUE TITLE
How to connect Spark containers to existing HDFS cluster?

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-spark#1]
Repo needs documentation on how to connect to existing HDFS cluster to read the data from.

HDFS can be deployed using docker with:
https://github.com/big-data-europe/docker-hadoop

Connection to HDFS can be performed in a same way as: https://github.com/big-data-europe/docker-hadoop-spark-workbench (using another Spark image build on top of docker-hadoop)

**Comment by erikap** [comment]
Hi @earthquakesan, 

in my opinion the connection to HDFS is the responsibility of the application. For example, in the [demo-spark-sensor-demo application](https://github.com/big-data-europe/demo-spark-sensor-data) the connection is setup in the [Application.java](https://github.com/big-data-europe/demo-spark-sensor-data/blob/master/src/main/java/com/tenforce/bde/spark/demo/sensors/Application.java#L64) and can be configured through the `HDFS_URL` environment variable (e.g. `hdfs://hdfs:9000`). I don't see how we can facilitate this through the Spark images.
