### ISSUE TITLE
Docker image does not exist

### ISSUE THREAD

**Issue by mariamunze** [big-data-europe/docker-spark#101]
Hi there,
first of all, great job. I really like your work.
However I met some problems with the docker versions for spark-worker and spark-master. It looks like the image tag: **3.0.0-hadoop3.2** does not exist. When I try with version 2.4.5 , then the image can be pulled. 

**Pulling spark-master (bde2020/spark-master:3.0.0-hadoop3.2)...
ERROR: manifest for bde2020/spark-master:3.0.0-hadoop3.2 not found: manifest unknown: manifest unknown**

**Comment by janarthanandev** [comment]
yes I am too facing same issue

**Comment by janarthanandev** [comment]
> 
> 
> Hi there,
> first of all, great job. I really like your work.
> However I met some problems with the docker versions for spark-worker and spark-master. It looks like the image tag: **3.0.0-hadoop3.2** does not exist. When I try with version 2.4.5 , then the image can be pulled.
> 
> **Pulling spark-master (bde2020/spark-master:3.0.0-hadoop3.2)... ERROR: manifest for bde2020/spark-master:3.0.0-hadoop3.2 not found: manifest unknown: manifest unknown**

Hi @mariamunze for time being change spark-worker image to  "image: bde2020/spark-worker:latest"

**Comment by mariamunze** [comment]
@janarthanandev  you can build the latest image version **3.0.0-hadoop3.2** with bash build.sh from the root directory. Thus this issue can be closed.

**Comment by janarthanandev** [comment]
@mariamunze can I have your yaml file for referrence

**Comment by GezimSejdiu** [comment]
Hi @mariamunze ,

thanks a lot for opening the issue. Indeed, that tag didn't exist on docker hub as the branch/tag was contributed via PR (thus not a dedicated branch was created for that tag which then triggers an automated build on docker-hub). I just did create such [a branch](https://github.com/big-data-europe/docker-spark/tree/3.0.0-hadoop3.2) from `master` and the build has been triggered on [Docker Hub](https://hub.docker.com/repository/docker/bde2020/spark-master).

PS: Thanks for your valuable comments @janarthanandev and helping @mariamunze to solve the issue.

I will close the issue for now but feel free to comment in case you can't pull the image and the issue persists.

Best regards,
Gezim
