### ISSUE TITLE
Asking for License's Information

### ISSUE THREAD

**Issue by jiahaoc1993** [big-data-europe/docker-spark#108]
Hi, project owners

What's the License of this project? I would like to know that will it cause any legal consequence if I package this project as part of my product?

**Comment by GezimSejdiu** [comment]
Hi @jiahaoc1993 , 

thanks a lot for your question and for using our docker images. At the beginning of the project, we decided to use MIT Licence (see the description: https://github.com/big-data-europe/README#license on README of the org). 

Hope that answer your questions, or you want to open a discussion if Apache 2.0 Licence vs MIT Licence is best for such kind of projects.

Best regards,

**Comment by jiahaoc1993** [comment]
@GezimSejdiu Thank you very mush for the answer. I think MIT license is good enough to save our time from discussion ;)
