### ISSUE TITLE
Pull request for 2.0.2-hadoop2.7

### ISSUE THREAD

**Issue by bilalakil** [big-data-europe/docker-spark#11]
Hi there,

Firstly, thanks for this awesome set of projects.

I [forked it and made a new branch for Spark 2.0.2-hadoop2.7](https://github.com/bilalakil/docker-spark/tree/2.0.2-hadoop2.7) which I'd like to submit a pull request for. However, I wasn't exactly sure how to go about that whilst maintaining that:

1. It's in a new branch: "2.0.2-hadoop2.7". I, understandably, cannot create branches here.
2. No strange Docker automatic builds happen. I don't know the settings that are in place in that regard.

How was this handled with the 2.0.1-hadoop2.7 branch? Shall we repeat history, or do you have another idea?

Regards,
Bilal.

**Comment by gezims** [comment]
Hi @bilalakil ,
many thanks for your contribution and using our spark docker image.
I will create a new branch `2.0.2-hadoop2.7` based on `2.0.1-hadoop2.7` branch and then you could submit a pull request for it.
I have tested out your branch and build all images locally and they worked :).
Regarding Automatic Build, after we will merge your pull request to the given branch, I will create 'tag' into the hub and then they will start triggering these changes over there.

Best regards,
Gezim

**Comment by bilalakil** [comment]
Awesome, I've made the PR. I suppose this issue is good to close then 😄
