### ISSUE TITLE
Spark 3.3.0

### ISSUE THREAD

**Issue by wparque** [big-data-europe/docker-spark#145]
Hello,

When will new image released with Spark 3.3.0?    We are in need of Spark 3.3.0 in order to remove log4j version 1 from image.

**Comment by GezimSejdiu** [comment]
Hi @wparque , 

thanks a lot for the issue and for requesting the image for Spark 3.3.0. I just added it here: https://github.com/big-data-europe/docker-spark/pull/147 and you should be able to use it already.
