### ISSUE TITLE
Spark UI has strange 'band' on top

### ISSUE THREAD

**Issue by arvindshmicrosoft** [big-data-europe/docker-spark#15]
Hi!
Firstly, thanks for providing these, they are very useful for getting started quickly with Spark.

However there is a minor issue: with any of the newer images (I have tried bde2020/spark-master:2.1.1-hadoop2.7, bde2020/spark-master:2.1.0-hadoop2.8-hive-java8, and latest) I am seeing a strange artifact on the top of the Spark UI. This happens whether I use Google Chrome or Microsoft Edge.

![capture](https://user-images.githubusercontent.com/16342666/27716458-639bc52a-5cf3-11e7-9bde-3f6f84cbcaae.PNG)

This causes an obvious usability problem because I can't see the other sections (like SQL / Executors etc.) Please suggest if I'm doing something wrong or if there is a known issue around this.

Thanks!

**Comment by earthquakesan** [comment]
Hi @arvindshmicrosoft!

You should not have this issue with the branch https://github.com/big-data-europe/docker-spark/tree/2.1.0-hadoop2.8-hive-java8
To run the docker images from this branch do:
```
make network
docker-compose -f docker-compose-minimal.yml up
```

Can you try this and see if you still have this problem?

**Comment by arvindshmicrosoft** [comment]
Looks good! Many thanks.

- Arvind Shyamsundar
