### ISSUE TITLE
hadoop 2.8.1

### ISSUE THREAD

**Issue by antonkulaga** [big-data-europe/docker-spark#16]
It would be nice to see hadoop 2.8.x support

**Comment by GezimSejdiu** [comment]
Hi @antonkulaga ,
many thanks for using BDE docker images!
Please have a look here [docker-spark-hadoop2.8](https://github.com/big-data-europe/docker-spark/tree/2.1.0-hadoop2.8-hive-java8), it is based on Spark 2.1.0 and build on hadoop2.8.0. 
Please, let me know if this is enough (since Spark [download](http://spark.apache.org/downloads.html) page does not support a pre-build with Hadoop 2.8.x) or we have to pre-build it by yourself and provide it on the separate branch.

**Comment by HashFail** [comment]
Hi @GezimSejdiu, do you perhaps have a Dockerfile or instructions you used for building spark with hadoop 2.8? Thanks!

**Comment by GezimSejdiu** [comment]
Hi @HashFail ,

I just created a branch which supports [Spark 2.3.1 with (user preferences) hadoop 2.8.0](https://github.com/big-data-europe/docker-spark/tree/2.3.1-hadoop2.8), could you give it a try and let us know if there are any issues. We use our[ bde hadoop-base image](https://github.com/big-data-europe/docker-hadoop/tree/1.2.0-hadoop2.8-java8) to build upon which brings the hadoop 2.8.0 on top of the Spark distribution. I double-check it and was able to see the configuration with Hadoop 2.8.0 when we launch one simple app via spark-shell on Spark. You could give it a try and let us know. 

PS: Many thanks @earthquakesan for your hints :) 

Best regards,

**Comment by HashFail** [comment]
Hi @GezimSejdiu, 

Thanks for your response! 

I noticed that the image the bde hadoop-base image is rather large (3.07 GB), and for our purposes it is rather important to optimize image size. After making some modifications to your base Spark 2.3.1 dockerfile, we were able to get the size down to ~1GB. I'll modify them to use your strategy of downloading the Spark and Hadoop binaries separately and see how that goes. 

Thanks again!

**Comment by GezimSejdiu** [comment]
Awesome! Looks like a good plan, please give it a try and let us know, we definitely could change something to reduce the size of the image, maybe we could consider to use openjdk:8-alpine as a smaller OS distribution. 

In case you, @antonkulaga can give it a try, would be great to have more feedbacks on the image.

many thanks for your comments.
