### ISSUE TITLE
spark submit configuration is not documented

### ISSUE THREAD

**Issue by JinnaBalu** [big-data-europe/docker-spark#18]
where can i find the docker-compose for spark submit? 

do we have any option to submit the job to the master.?

**Comment by GezimSejdiu** [comment]
Hi @JinnaBalu ,
many thanks for using BDE components. If you were asking for How To submit spark jobs over [spark-submit image](https://github.com/big-data-europe/docker-spark/tree/master/submit) there is this [demo example](https://github.com/big-data-europe/demo-spark-sensor-data) using [Maven template image](https://github.com/big-data-europe/docker-spark/tree/master/template/java),  which shows exactly that, and it has [docker-compose](https://github.com/big-data-europe/demo-spark-sensor-data/blob/master/docker-compose.yml) file which shows how you specify your [job](https://github.com/big-data-europe/demo-spark-sensor-data/blob/master/docker-compose.yml#L75) to be linked to spark-master.
Please, have a look at this [blog post](https://www.big-data-europe.eu/developing-spark-applications-with-docker-and-bde/) as well for more easy steps on how to do it.

Let us know if you need more hints on how to use spark-submit.
Best regards,

**Comment by earthquakesan** [comment]
Hi @JinnaBalu!

You can also find sbt example [here](https://github.com/earthquakesan/TwitterTrends).
