### ISSUE TITLE
question to environment configuration

### ISSUE THREAD

**Issue by 1605200517** [big-data-europe/docker-spark#19]
How do I read this environment setting:

`"constraint:node==<yourmasternode>"`?

I mean, in a Docker Spark environment you would just have a master node and a set of worker nodes, or?

**Comment by earthquakesan** [comment]
Hi!

That's a typical constraint for swarm deployment (prior to swarm mode). Here are [the docs](https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint).
