### ISSUE TITLE
Support for Spark 2.2.2, 2.1.3, and 2.1.2

### ISSUE THREAD

**Issue by shimamoto** [big-data-europe/docker-spark#32]
Hi all,

I would like to propose to push some additional docker images to your Docker Hub.

My suggestions are as follows:

- 2.2.2-hadoop2.7
- 2.1.3-hadoop2.7
- 2.1.2-hadoop2.7

Do you guys think about adding this versions? If so, can I contribute for it with a PR?

Many thanks!

**Comment by GezimSejdiu** [comment]
Hi @shimamoto ,

sure why not! That would be a great contribution to the project. Please, create a dedicated branch for each of the supports by deriving it from one version down (just in case you want to know the process). 

Best,

**Comment by shimamoto** [comment]
@GezimSejdiu I tried my hand at 2.2.2-hadoop2.7

https://github.com/shimamoto/docker-spark/commit/a867fd8796b35e7126ac7a77bd5bdbb9da6b174b

I created a branch from the 2.2.1-hadoop2.7. Is that correct?

**Comment by GezimSejdiu** [comment]
Great!
Yes, that is correct! Feel free to create PR for it  :)

**Comment by shimamoto** [comment]
All done!

@GezimSejdiu Thank you so much!
