### ISSUE TITLE
Validating if step spark_master_init can start in pipeline

### ISSUE THREAD

**Issue by scalessio** [big-data-europe/docker-spark#37]
Hi everyone,
I'm just try to use this images to run a simple application using the containers.
After clone the repository at 
https://github.com/big-data-europe/docker-spark

I have run the docker compose. The container with master and worker was up and running, the worker was successfully registered at the master.
After I had created a python application to run it on spark-container.
The image that submit the application is bd2020/spark-submit, I just add the ENV variable as like as wrote in the README.
When i run the container with the command: 

sudo docker run --network=docker-spark_default --name my_container  --link spark-master:spark-master my_image

Appears:
Validating if step spark_master_init can start in pipeline

and nothings work. There is something wrong?

**Comment by GezimSejdiu** [comment]
Hi @scalessio ,

many thanks for using our docker images. 
Based on your docker run command and the logs seems that you are missing an environment which disable the Init daemon service (which waits for a command to start the docker). 
Could you please use this command instead and let us know if there are still issues. 

```sh
sudo docker run --network=docker-spark_default --name my_container --link spark-master:spark-master -e ENABLE_INIT_DAEMON=false my_image
```

Best regards,
Gezim

**Comment by GezimSejdiu** [comment]
Hi @scalessio ,

were you able to compose up the pipeline when disabling the init_deamon flag? If so, could you please let us know with the latest status.

Best regards,

**Comment by ImScientist** [comment]
Hi @GezimSejdiu ,

thanks for the tip. 
I had the same problem. In my case I have started a single spark-master with:
```
docker run --name spark-master -h spark-master -e ENABLE_INIT_DAEMON=false -d bde2020/spark-master:2.3.0-hadoop2.7
```

The addition of **-e ENABLE_INIT_DAEMON=false** solved my problem:
```
docker run --name my-spark-app --link spark-master:spark-master -e ENABLE_INIT_DAEMON=false bde/spark-app
```

But I got other problems for which I have to open another issue.
