### ISSUE TITLE
Start Master with a properties-file

### ISSUE THREAD

**Issue by haimomesi** [big-data-europe/docker-spark#38]
I would like to use ZooKeeper for High-Availability of Master.

In order to do that, I've create a `ha.conf` file: 

`spark.deploy.recoveryMode=ZOOKEEPER`
`spark.deploy.zookeeper.url=<zookeeper_host>:2181`
`spark.deploy.zookeeper.dir=/spark`

The next step is to start-master.sh with **--properties-file ha.conf**
but I couldn't find any way to do that here

Thank you in advance,
Haim

**Comment by GezimSejdiu** [comment]
Hi @haimomesi , 

is this still valid? Can we use our introduced ARG ENV:  2662a78 .

One example of how to use could be:
```
ENV SPARK_SUBMIT_ARGS "--spark.deploy.recoveryMode=ZOOKEEPER --spark.deploy.zookeeper.url=zookeeper_host>:2181 --spark.deploy.zookeeper.dir=/spark"
```
or to a mounted file (you mount it withing the docker which contains these info and then add it to the ENV):
```
ENV SPARK_SUBMIT_ARGS "---properties-file /path/to/mounted/volume/ha.conf"
```
Do let me know if you think we can have this into our radar.
Best regards,
