### ISSUE TITLE
passing the spark configuration properties to the dockerized spark

### ISSUE THREAD

**Issue by ritikam2** [big-data-europe/docker-spark#39]
Hi,
     I am not sure how to pass spark properties like
spark.executor.memory
spark.driver.memory ....
to docker-spark. 

In the compose file I see we can pass the env file

spark-master:
        image: 'bde2020/spark-master:2.1.0-hadoop2.8-hive-java8'
        container_name: spark-master
        ports:
            - '8080:8080'
            - '7077:7077'
        
        env_file:
            - ./hadoop.env

but this env file does not tell how to pass spark properties. It has prefixes like CORE_CONF , HIVE_SITE_CONF, HDFS_CONF, YARN_CONF but it does not tell how to pass Spark conf properties.
Could we just append them with SPARK_CONF.
So SPARK_CONF_spark_driver_memory?

**Comment by GezimSejdiu** [comment]
Hi @ritikam2 

many thanks for using our Spark docker images. This can be done by specifying the `SPARK_SUBMIT_ARGS` variable on the environment variables (see here https://github.com/big-data-europe/docker-spark/blob/master/submit/submit.sh#L16 for more details). 

This question pushes us to document this process on [templates](https://github.com/big-data-europe/docker-spark/tree/master/template).

Let us know if there is still some more help needed from our end.

Best regards,

**Comment by ritikam2** [comment]
thanks for the update

**Comment by GezimSejdiu** [comment]
Hi @ritikam2 ,

could you let us know if you were able to pass the Spark configurations on spark submit? If so, can we consider closing this issue?

Best regards,

**Comment by ritikam2** [comment]
Yes please. Thanks

Ritika

**Comment by karrtikiyer** [comment]
Hi @GezimSejdiu , if I am running a python/scala jupyter notebook against this spark docker instance, how would I pass executor memory or driver memory?

**Comment by purbanow** [comment]
+1
