### ISSUE TITLE
No spark-submit image for 2.3.2-hadoop2.7 

### ISSUE THREAD

**Issue by britishbadger** [big-data-europe/docker-spark#45]
Hi, recently discovered your great images but the following build failed https://hub.docker.com/r/bde2020/spark-submit/builds/bvs3y3w8bvqqvvhsau8hev9/ , guess it was an ordering thing as the image it failed on seems to be there now. 

This means you can't follow the submit instructions without building the the submit and template images first

**Comment by GezimSejdiu** [comment]
Hi @britishbadger ,

many thanks for using our Spark docker images. Yes, you are right. There was an issue with the trigger ordering for Automatic Build. I just triggered them manually for [bde2020/spark-submit](https://hub.docker.com/r/bde2020/spark-submit/builds/), [bde2020/spark-java-template](https://hub.docker.com/r/bde2020/spark-java-template/builds/) and [bde2020/spark-python-template](https://hub.docker.com/r/bde2020/spark-python-template/builds/).

Many thanks for letting us know!
In case you are able to pull these images, please consider closing the issue afterward :) 

Best regards,

**Comment by britishbadger** [comment]
Thanks it seems to work
