### ISSUE TITLE
python3.4 can not run in docker-spark

### ISSUE THREAD

**Issue by Benknightdark** [big-data-europe/docker-spark#5]
Hello, I create a Spark standalone cluster from docker-spark, and then, I use python 3.4 to execute some code , but it export some errors.
![image](https://cloud.githubusercontent.com/assets/5799487/17993483/b567eb94-6b82-11e6-87ab-5d368153dbec.png)
How could I use python 3.4 to Build the spark application from the docker-spark？

**Comment by erikap** [comment]
Hi @Benknightdark, unfortunately the Spark docker currently only supports Java. Support for Scala and Python will be added in the near future.

**Comment by erikap** [comment]
Hi @Benknightdark, thanks to @cecton the Spark docker supports python. Have a look at the [Spark Python template README](https://github.com/big-data-europe/docker-spark/tree/master/template/python) to get started.
