### ISSUE TITLE
Image for Spark 2.4.0 and Scala 2.12.X

### ISSUE THREAD

**Issue by oscarvarto** [big-data-europe/docker-spark#53]
Spark 2.4.0 has introduced official (and experimental) support for Scala 2.12.

It would be awesome to have an image for those (a lot!) interested in support for the current stable version of Scala.
My hunch is that this could be another incentive to adopt Spark.

Thanks in advance!

**Comment by GezimSejdiu** [comment]
Hi @oscarvarto ,
many thanks for your suggestion. We already discussed that idea here and we provide a docker image for [spark2.4.0-hadoop2.8-scala.2.12](https://github.com/big-data-europe/docker-spark/tree/2.4.0-hadoop2.8-scala2.12). Please, have a look at #49 . Let us know if you try it out and how it is working. 

Best regards,

**Comment by oscarvarto** [comment]
Will try it tomorrow asap!

Thanks for the quick response.
