### ISSUE TITLE
spark-submit 2.4.0-hadoop2.8 looks to be using spark 2.3.2

### ISSUE THREAD

**Issue by thekj** [big-data-europe/docker-spark#54]
Got an error when running a spark jobs with the new `foreachBatch` feature using the new 2.4.0.

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.streaming.DataStreamWriter.foreachBatch(Lorg/apache/spark/api/java/function/VoidFunction2;)Lorg/apache/spark/sql/streaming/DataStreamWriter;
```

There possibly could have been a race condition when the submit image was being rebuilt with 2.4.0:

1: Base image built using 2.3.2 with 2.4.0-hadoop2.8 tag
https://hub.docker.com/r/bde2020/spark-base/builds/bmyk2bwzrf45mtnm2zwj5d7/ 

2a: Create submit built using current 2.4.0-hadoop2.8 tag
https://hub.docker.com/r/bde2020/spark-submit/builds/bs2wmyvasv3mys5liazbp2f/

2b: Rebuilding 2.4.0-hadoop2.8 tag with 2.4.0
https://hub.docker.com/r/bde2020/spark-base/builds/b9qiydy4a2k6xfx3mfkizdn/

Would it be possible to trigger the spark-submit image to get rebuilt?

**Comment by sakthig** [comment]
Hi @thekj what was the issue., facing same on 2.4.3

**Comment by suniljangraLTI** [comment]
Hi, I am getting same exception after changing spark version from 2.4.7 to 2.4.8. Can you tell me how did you solve this issue.
