### ISSUE TITLE
Spark Python template

### ISSUE THREAD

**Issue by ImScientist** [big-data-europe/docker-spark#56]
Hi, 

I had the following problem when trying to use the [Spark Python template](https://github.com/big-data-europe/docker-spark/tree/master/template/python) to run a Spark application on top of the Spark cluster.

The [submit.sh](https://github.com/big-data-europe/docker-spark/blob/master/submit/submit.sh) file that is executed from [template.sh](https://github.com/big-data-europe/docker-spark/blob/master/template/python/template.sh) that is executed from this [Dockerfile](https://github.com/big-data-europe/docker-spark/blob/master/template/python/Dockerfile#L4) can not find the file **app/app.py** which is the value of the env variable **SPARK_APPLICATION_PYTHON_LOCATION** (see line 19 in [submit.sh](https://github.com/big-data-europe/docker-spark/blob/master/submit/submit.sh) ). The problem is solved after replacing **ONBUILD COPY** with **COPY** in the Dockerfile. 

In addition, the python packages in requirements.txt were also not installed. To solve the problem I had to add the following lines before line 19 in submit.sh: 
```
cd /app 
pip3 install -r requirements.txt 
cd ..
```

The Dockerfile that I used (instead of [this](https://github.com/big-data-europe/docker-spark/blob/master/template/python/Dockerfile#L4)) is given below:
```
FROM bde2020/spark-submit:2.3.0-hadoop2.7

COPY template.sh /
COPY requirements.txt /app/requirements.txt
COPY app.py /app/app.py
COPY submit.sh /submit.sh

ENV SPARK_APPLICATION_PYTHON_LOCATION /app/app.py

CMD ["/bin/bash", "/template.sh"]
```
The submit.sh file that I used is given below:
```
#!/bin/bash

export SPARK_MASTER_URL=spark://${SPARK_MASTER_NAME}:${SPARK_MASTER_PORT}
export SPARK_HOME=/spark

/wait-for-step.sh


/execute-step.sh


cd /app 
pip3 install -r requirements.txt
cd ..

if [ -f "${SPARK_APPLICATION_JAR_LOCATION}" ]; then
    echo "Submit application ${SPARK_APPLICATION_JAR_LOCATION} with main class ${SPARK_APPLICATION_MAIN_CLASS} to Spark master ${SPARK_MASTER_URL}"
    echo "Passing arguments ${SPARK_APPLICATION_ARGS}"
    /spark/bin/spark-submit \
        --class ${SPARK_APPLICATION_MAIN_CLASS} \
        --master ${SPARK_MASTER_URL} \
        ${SPARK_SUBMIT_ARGS} \
        ${SPARK_APPLICATION_JAR_LOCATION} ${SPARK_APPLICATION_ARGS}
else
    if [ -f "${SPARK_APPLICATION_PYTHON_LOCATION}" ]; then
        echo "Submit application ${SPARK_APPLICATION_PYTHON_LOCATION} to Spark master ${SPARK_MASTER_URL}"
        echo "Passing arguments ${SPARK_APPLICATION_ARGS}"
        PYSPARK_PYTHON=python3 /spark/bin/spark-submit \
            --master ${SPARK_MASTER_URL} \
            ${SPARK_SUBMIT_ARGS} \
            ${SPARK_APPLICATION_PYTHON_LOCATION} ${SPARK_APPLICATION_ARGS}
    else
        echo "Not recognized application."
    fi
fi
/finish-step.sh
```

The application app.py was launched, as described in the notes ([docker-spark](https://github.com/big-data-europe/docker-spark), [spark-python](https://github.com/big-data-europe/docker-spark/tree/master/template/python)) , but with the addition of **-e ENABLE_INIT_DAEMON=false** (see this [issue](https://github.com/big-data-europe/docker-spark/issues/37) ):
```
docker pull bde2020/spark-master:2.3.0-hadoop2.7

docker run --name spark-master -h spark-master -e ENABLE_INIT_DAEMON=false -d bde2020/spark-master:2.3.0-hadoop2.7

docker build --rm -t bde/spark-app .

docker run --name my-spark-app --link spark-master:spark-master -e ENABLE_INIT_DAEMON=false bde/spark-app
```

**Comment by GezimSejdiu** [comment]
Hi @ImScientist ,
Happy New Year! This is great! Many thanks for your contribution. I do agree with you that the basic setup installation was missing on the Python template image. Please, consider pushing this as a PR and will be happy to review and merge it. You could target any other branch, besides the master branch.

Best regards,

**Comment by casperlehmann** [comment]
Hi all. Very nice work on this project!

I found this out as well. However, I'm a bit puzzled as to whether this is the recommended way of submitting python files.
On one hand the name of the directory is "template," so it would be easy to suppose that I should be editing it's content directly. But on the other hand the "Spark Python template Docker image" referred to in the readme seems to mean the "Example Dockerfile," which is supposed to be part of the "Example application" (Coming soon).
So, can someone please clarify if I'm supposed to create a new docker project inheriting from bde2020/spark-python-template:2.4.0-hadoop2.7 as described in the readme, or if I'm supposed to edit this template directory as described above?

I'm supposing that the "right" way to do it is to create a new project, but if that is the case, does the name "template" of the directory not seem confusing? "Spark Python template Docker image" might refer to either the Docker image created from the template directory or from the Dockerfile example at the bottom of the page.

**Comment by GezimSejdiu** [comment]
Hi @casperlehmann , 

thanks a lot for your comment. I have also provided [one Python example](https://github.com/big-data-europe/docker-spark/tree/master/examples/python) with a guide on how to use the template. Feel free to look into it and do let me know if there is something else missing.

Best regards, 
Gezim
