### ISSUE TITLE
Image for Spark 2.4.0 and Hadoop 3.0+

### ISSUE THREAD

**Issue by xuexuemiao** [big-data-europe/docker-spark#57]
Hadoop 3.0+ introduced native support for aliyun oss, for now it's hard to solve all dependency problem from integrating spark and aliyun oss.

**Comment by GezimSejdiu** [comment]
Hi @xuexuemiao ,

many thanks for the suggestion of having a Spark docker image for Hadoop 3.+. I just created a branch `[2.4.0-hadoop3.1](https://github.com/big-data-europe/docker-spark/tree/2.4.0-hadoop3.1). Please, give it a try and let us know if it is working.

Best regards,

**Comment by GezimSejdiu** [comment]
@xuexuemiao ,
I'm going to close this issue for now. Please, give it a try and let us know if there is something else missing for Hadoop 3.x support.

Best regards,

**Comment by xuexuemiao** [comment]
@GezimSejdiu 
Thanks for this special branch! And I'm so sorry for the late reply after long vacation. I will try it ASAP and let you know the result.

**Comment by GezimSejdiu** [comment]
Great! 

Give it a try and let us know :) 

Best regards,
