### ISSUE TITLE
Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

### ISSUE THREAD

**Issue by alexfdezsauco** [big-data-europe/docker-spark#59]
I'm running into an issue when try to submit a job in client mode against a standalone cluster or just open the spark-shell. I just get an warning this warning message:

> Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

and the job never execute, but never ends, it just retry to execute the job again. 

if I set deploy-mode to cluster, the job works.

I deploy the standalone cluster locally using docker-compose and also in DC/OS (marathon).

Any idea?

**Comment by market07** [comment]
Did you solve this problem?

**Comment by hyybblover** [comment]
I have the same question .
`19/05/14 16:00:22 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
`

**Comment by pacien** [comment]
Hello,

I've experienced the described issue on my deployment with one master and multiple workers on Rancher/Kubernetes, with enough resources to run a test spark app.

In my case, the problem lied in my network: the driver running in client mode on my machine was able to reach the master and worker nodes, but the worker nodes weren't able to reach my machine back, resulting in the cited error message being shown on the latter, and the job being stuck in a retry loop.

You might want to enter a shell in one of the worker containers and check that it is able to reach the machine on which the driver runs.

**Comment by YuseqYaseq** [comment]
I had a similar problem and it turned out that master was unable to reach workers. So make sure to check it the other way around too i.e. check if spark worker logs something like "INFO Worker: Asked to launch executor ... on worker ...".

**Comment by aman1505** [comment]
Whats the resolution for this problem, I am also facing similar issue

**Comment by PN25030** [comment]
I am facing same issue.
