### ISSUE TITLE
Spark 2.4.1

### ISSUE THREAD

**Issue by antonkulaga** [big-data-europe/docker-spark#69]
it would be nice to see Spark 2.4.1 images as there were fixes of some annoying bugs there

**Comment by pacien** [comment]
Or even 2.4.2 and 2.4.3 that are now both available!

**Comment by gmouchakis** [comment]
Spark 2.4.1 was merged into master so i'm closing this. Spark 2.4.2 and 2.4.3 will be added in the future.
