### ISSUE TITLE
About spark submit

### ISSUE THREAD

**Issue by uniysfu** [big-data-europe/docker-spark#82]
I have run the spark master container. If I need to submit an application, shall I use the spark submit  script in the spark master or shall I run the spark submit container to submit my application?

**Comment by gmouchakis** [comment]
Hi @uniysfu, whatever suits you better, both approaches work.

**Comment by hossein-kshvrz** [comment]
@gmouchakis is there any other option? I want to embed a python module, which needs Pyspark to work, in a Django project. What do you think is the best way to run my module?

**Comment by gmouchakis** [comment]
@hossein-kshvrz I suppose the easiest solution would be to create an image with everything you need for your application and then start a container that can reach the spark master. Note that I don't have experience with Django so maybe you should ask elsewhere for advice on this.
